default['split_mongodb_json']['application']     = "symphony"
default['split_mongodb_json']['ip_address']     = "13.71.151.57"
default['split_mongodb_json']['port']     = "27017"
default['split_mongodb_json']['username']    = "qaadmin"
default['split_mongodb_json']['password'] = "password"
default['split_mongodb_json']['database'] = "journaldev"
default['split_mongodb_json']['collection'] = "dataset"
default['split_mongodb_json']['max_size_in_mb'] = "3"
